# Generated by Django 5.2.4 on 2025-07-12 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katalogi', '0001_initial'),
        ('tseny', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prices',
            new_name='Tseny',
        ),
    ]
