# Generated by Django 5.2.4 on 2025-07-12 11:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GruppaNomenklatury',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('naimenovanie', models.CharField(max_length=250, verbose_name='Наименование')),
                ('roditel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='katalogi.gruppanomenklatury', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Группа номенклатуры',
                'verbose_name_plural': 'Группа номенклатуры',
            },
        ),
        migrations.CreateModel(
            name='Nomenklatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('polnoe_naimenovanie', models.CharField(max_length=250, verbose_name='Наименование')),
                ('roditel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='katalogi.gruppanomenklatury', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
            },
        ),
    ]
