# Generated by Django 5.2.4 on 2025-07-13 20:12

import django.db.models.deletion
import katalogi.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalogi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kartinki',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kartinka', models.ImageField(default=None, upload_to=katalogi.models.put_k_papke_kartinok, verbose_name='Картинка')),
                ('nomenklatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_images', to='katalogi.nomenklatura', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинка',
            },
        ),
    ]
